### ISSUE TITLE
Add party logo to member portraits

### ISSUE THREAD

**Issue by jampekka** [kansanmuisti/kamu#123]

**Comment by juyrjola** [comment]
Front page done, at least topic page still needs work.

**Comment by terotic** [comment]
Topic page done. Uses same template and style as front page. Green party used as placemarker as the page doesn't read party logo yet (?) Also set the photo to scale 100% width, we should bring a bit larger res photo on the page to accomodate bigger element widths.

**Comment by jampekka** [comment]
Needs a pile of hacks for a simple damn url to get to the href. I cannot due it because I could go to psychosis if I'd have to code the stuff this requires.
