### ISSUE TITLE
Feed view filter box redesign

### ISSUE THREAD

**Issue by terotic** [kansanmuisti/kamu#126]
Sticky on sidebar?

**Comment by jampekka** [comment]
I'd put this sticky on top, at least on desktop resolutions.

**Comment by jampekka** [comment]
@terotic Now party and member pages use the common stuff. Also moved the filter bar on top of the stream. Probably some kind of visual indication that this is a "header" for the plot/stream panel would be nice.

Could IMHO also use the horisontal estate better, especially when it becomes fixed-on-top

**Comment by jampekka** [comment]
The tagcloud as a filter is confusing as Tero predicted. Perhaps a nicer interaction would be to send the user to a member/party filtered topic activity page by clicking on it.

**Comment by jampekka** [comment]
As Tero predicted, the tag cloud as filter is indeed quite confusing in my mind also even after a separate box. A nicer interaction would probably be to send the user to the MP/Party-filtered topic page. This would also be more consistent with the upcoming deep linkings. Technically the MP/Party filter would be quite easy. Also it could use the autocomplete that is already there for the search box.

**Comment by jampekka** [comment]
I'd also consider moving the tag cloud to the sidebar on desktop, as it has currently very little content anyway, and this would be more compatible with the topic view's structure.

**Comment by jampekka** [comment]
I'm mostly done with this for now. I think the keyword should be a lot more prominent (almost like a title) and the date filtering could be hidden behind a button by default (the button could indicate if the date filtering is active or not), as custom filtering isn't probably a very common use case.

**Comment by jampekka** [comment]
Probably finally done
