### ISSUE TITLE
Implement social media share buttons

### ISSUE THREAD

**Issue by juyrjola** [kansanmuisti/kamu#139]

**Comment by terotic** [comment]
Added on member, document and issue pages. The button should be close to the page title so the user knows what they are sharing.

I would prefer a button with the service icons visible, this button is not very recognisable. And preferably with counter.

This one is okish and doesnt need commitment to a service provider:
http://sharrre.com/

Sharethis and Addthis offer smooth and familiar ui, but are third party services.
