### ISSUE TITLE
Design bookmark and social media share icons

### ISSUE THREAD

**Issue by juyrjola** [kansanmuisti/kamu#157]
FB:
Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images.

Try to keep your images as close to 1.91:1 aspect ratio as possible to display the full image in News Feed without any cropping.

Phones:
Retina icons 114x114px

**Comment by terotic** [comment]
Still needs to pull page title,  description and preferred content image if available to og meta tags.
