### ISSUE TITLE
Leave feedback functionality

### ISSUE THREAD

**Issue by juyrjola** [kansanmuisti/kamu#166]

**Comment by jampekka** [comment]
Please add some kind of spam prevention mechanism this time. Previous feedback started going to trash folder because of the spam.

I think this should maybe be public. I think some kind of generic discussion component would be nice.

**Comment by terotic** [comment]
Something like this?
https://developers.facebook.com/docs/plugins/comments

**Comment by terotic** [comment]
Added fb social plugin on info page.
